plugins { id 'com.android.application' }

android {
    namespace 'fr.prendresoindesonhetre.monoxygene.v40'
    compileSdk 35

    defaultConfig {
        applicationId 'fr.prendresoindesonhetre.monoxygene.enchainementsv42'
        minSdk 23
        targetSdk 35
        versionCode 42
        versionName '1.0.42'
    }
}
