plugins { id 'com.android.application' }

android {
    namespace 'fr.prendresoindesonhetre.monoxygene.v40'
    compileSdk 35

    defaultConfig {
        applicationId 'fr.prendresoindesonhetre.monoxygene.enchainementsv41'
        minSdk 23
        targetSdk 35
        versionCode 41
        versionName '1.0.41'
    }
}
