plugins { id 'com.android.application' }

android {
    namespace 'fr.prendresoindesonhetre.monoxygene'
    compileSdk 35

    defaultConfig {
        applicationId 'fr.prendresoindesonhetre.monoxygene'
        minSdk 19
        targetSdk 35
        versionCode 36
        versionName '1.0.36'
    }
}
